#ifndef TABBEDEDITOR_GLOBAL_H
#define TABBEDEDITOR_GLOBAL_H

#include <QtGlobal>

#if defined(TABBEDEDITOR_LIBRARY)
#  define TABBEDEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TABBEDEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TABBEDEDITOR_GLOBAL_H

